// --------------------------------------------------------------------------------------------------------------------
// <copyright file=" ProductRepository.cs" company="EPIC Software">
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <summary>
//  Contributors: Roy Gonzalez
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Epic.Sample.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    using Epic.Sample.Domain.Entities;
    using Epic.Sample.Domain.Repository;

    using LiteDB;

    /// <summary>
    /// Class ProductRepository.
    /// Implements the <see cref="Epic.Sample.Domain.Repository.IProductRepository" />
    /// </summary>
    /// <seealso cref="Epic.Sample.Domain.Repository.IProductRepository" />
    /// <autogeneratedoc />
    public class ProductRepository : IProductRepository
    {
        /// <summary>
        /// The database
        /// </summary>
        /// <autogeneratedoc />
        private readonly LiteRepository db;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductRepository"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public ProductRepository()
        {
            this.db = new LiteRepository("local");
        }

        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <autogeneratedoc />
        public void Delete(Guid id)
        {
            this.db.Delete<Product>(id);
        }

        /// <summary>
        /// Finds the specified query.
        /// </summary>
        /// <param name="query">The query.</param>
        /// <returns>The Product.</returns>
        /// <autogeneratedoc />
        public Product Find(Expression<Func<Product, bool>> query)
        {
            return this.db.Query<Product>().Where(query).FirstOrDefault();
        }

        /// <summary>
        /// Finds all.
        /// </summary>
        /// <param name="query">The query.</param>
        /// <returns>IEnumerable Product .</returns>
        /// <autogeneratedoc />
        public IEnumerable<Product> FindAll(Expression<Func<Product, bool>> query)
        {
            return this.db.Query<Product>().Where(query).ToList();
        }

        /// <summary>
        /// Finds all.
        /// </summary>
        /// <returns>IEnumerable Product.</returns>
        /// <autogeneratedoc />
        public IEnumerable<Product> FindAll()
        {
            return this.db.Query<Product>().ToList();
        }

        /// <summary>
        /// Saves the specified product.
        /// </summary>
        /// <param name="product">The product.</param>
        /// <autogeneratedoc />
        public void Save(Product product)
        {
            this.db.Insert(product);
        }

        /// <summary>
        /// Updates the specified product.
        /// </summary>
        /// <param name="product">The product.</param>
        /// <autogeneratedoc />
        public void Update(Product product)
        {
            this.db.Update(product);
        }
    }
}