// --------------------------------------------------------------------------------------------------------------------
// <copyright file=" Entity.cs" company="EPIC Software">
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <summary>
//  Contributors: Roy Gonzalez
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Epic.Sample.Domain.Entities
{
    using System;

    /// <summary>
    ///     The entity is the abstract class for every domain class
    /// </summary>
    /// <summary>
    /// Class Entity.
    /// </summary>
    /// <autogeneratedoc />
    public abstract class Entity
    {
        /// <summary>
        /// sets or gets the id of the entities
        /// </summary>
        /// <value>The identifier.</value>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets the identity.
        /// </summary>
        /// <value>The identity.</value>
        /// <autogeneratedoc />
        public string Identity => this.Id.ToString();
    }
}