// --------------------------------------------------------------------------------------------------------------------
// <copyright file=" ProductType.cs" company="EPIC Software">
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <summary>
//  Contributors: Roy Gonzalez
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Epic.Sample.Application.Models
{
    using Epic.Sample.Domain.Entities;

    using GraphQL.Types;

    /// <summary>
    /// Class ProductType.
    /// Implements the <see>
    ///         <cref>GraphQL.Types.ObjectGraphType{Epic.Sample.Domain.Entities.ProductUpdate}</cref>
    ///     </see>
    /// </summary>
    /// <seealso>
    ///     <cref>GraphQL.Types.ObjectGraphType{Domain.Entities.ProductUpdate}</cref>
    /// </seealso>
    /// <autogeneratedoc />
    public class ProductType : ObjectGraphType<Product>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductType"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public ProductType()
        {
            this.Field(x => x.Identity);
            this.Field(x => x.Name);
            this.Field(x => x.Price);
            this.Field(x => x.Quantity);
        }
    }
}