// --------------------------------------------------------------------------------------------------------------------
// <copyright file=" NewProduct.cs" company="EPIC Software">
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
// </copyright>
// <summary>
//  Contributors: Roy Gonzalez
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Epic.Sample.Application.Commands
{
    using MediatR;

    /// <summary>
    /// Class NewProduct.
    /// Implements the <see cref="MediatR.IRequest" />
    /// </summary>
    /// <seealso cref="MediatR.IRequest" />
    /// <autogeneratedoc />
    public class NewProduct : IRequest
    {
        /// <summary>
        /// Gets or sets the price.
        /// </summary>
        /// <value>The price.</value>
        /// <autogeneratedoc />
        public float Price { get; set; }

        /// <summary>
        /// Gets or sets the product.
        /// </summary>
        /// <value>The product.</value>
        /// <autogeneratedoc />
        public string Product { get; set; }

        /// <summary>
        /// Gets or sets the quantity.
        /// </summary>
        /// <value>The quantity.</value>
        /// <autogeneratedoc />
        public float Quantity { get; set; }
    }
}